services:
    sio_test:
        user: app
        build:
            context: .
            args:
                USER_ID: ${USER_ID:-1000}
        ports:
            - "8337:8337"
        volumes:
            - .:/app:rw
        environment:
            - APP_ENV=dev
            - DATABASE_URL=${DATABASE_URL}

    database:
      image: postgres:${POSTGRES_VERSION:-16}-alpine
      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
      volumes:
        - database_data:/var/lib/postgresql/data:rw

volumes:
  database_data:
